---
- include: install.yml
  tags:
    - install

- include: configure.yml
  tags:
    - configure

- include: deploy.yml
  tags:
    - deploy

- include: test.yml
  when: >
    (couchdb_host_address) and
    (couchdb_port) and
    (couchdb_test_http_status_code) and
    (couchdb_test_string)
  tags:
    - test
